apiVersion: v1
kind: Secret
metadata:
  name: api-keys
  namespace: ecommerce
type: Opaque
data:
  jwt-secret: bXlzdXBlcnNlY3JldGp3dGtleWZvcmF1dGhlbnRpY2F0aW9u  # mysupersecretjwtkeyforauthentication
  stripe-api-key: c2tfdGVzdF80ZUFhbmQ5WWRGUG1XR2hsZ3VnMURTcVk=  # sk_test_4eAan...
  redis-password: cmVkaXNwYXNzd29yZA==  # redispassword
  encryption-key: bXlzdXBlcnNlY3JldGVuY3J5cHRpb25rZXk=  # mysupersecretencryptionkey