apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: ecommerce
type: Opaque
data:
  username: ZWNvbW1lcmNl  # ecommerce
  password: ZWNvbW1lcmNlcGFzcw==  # ecommercepass
  database: ZWNvbW1lcmNlX2Ri  # ecommerce_db
  postgres-password: c2VjcmV0cGFzc3dvcmQ=  # secretpassword